/********************************************************************************
** Form generated from reading UI file 'hapticevaluationgui.ui'
**
** Created: Thu 8. Oct 16:57:06 2015
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HAPTICEVALUATIONGUI_H
#define UI_HAPTICEVALUATIONGUI_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_HapticEvaluationGUIClass
{
public:
    QWidget *centralWidget;
    QPushButton *pushButtonStart;
    QPushButton *pushButtonStop;
    QLabel *labelStatus;
    QwtPlot *qwtPlot;
    QCheckBox *checkBoxFxA;
    QCheckBox *checkBoxFyA;
    QCheckBox *checkBoxFzA;
    QCheckBox *checkBoxFtotalA;
    QCheckBox *checkBoxFxB;
    QCheckBox *checkBoxFyB;
    QCheckBox *checkBoxFzB;
    QCheckBox *checkBoxFtotalB;
    QFrame *frameHaptBCtrl;
    QLabel *label_15;
    QLineEdit *lineEditEntactBIP;
    QLabel *label_19;
    QCheckBox *checkBoxActiveEntactB;
    QPushButton *pushButtonEntactBCalibrate;
    QFrame *frameHaptACtrl;
    QLabel *label_17;
    QLabel *label_18;
    QCheckBox *checkBoxActiveEntactA;
    QLineEdit *lineEditEntactAIP;
    QPushButton *pushButtonEntactACalibrate;
    QLabel *label_25;
    QTextEdit *textEditExpInfo;
    QFrame *frame;
    QLineEdit *lineEditLJSerialA;
    QCheckBox *checkBoxAtiActivateA;
    QLabel *label_27;
    QFrame *frame_2;
    QLineEdit *lineEditLJSerialB;
    QCheckBox *checkBoxAtiActivateB;
    QLabel *label_28;
    QFrame *frame_3;
    QLabel *labelFile;
    QLineEdit *lineEditLog;
    QLabel *labelFile_4;
    QRadioButton *radioButtonRight;
    QRadioButton *radioButtonLeft;
    QLabel *label_29;
    QFrame *frame_4;
    QLabel *label_14;
    QRadioButton *radioButtonSLPosition;
    QRadioButton *radioButtonSLForce;
    QRadioButton *radioButtonDLForce;
    QRadioButton *radioButtonHaptRep;
    QRadioButton *radioButtonATIOnly;
    QRadioButton *radioButtonHRSeq;
    QRadioButton *radioButtonHaptRepAuto;
    QRadioButton *radioButtonSingleHaptic;
    QRadioButton *radioButtonDepthConstant;
    QRadioButton *radioButtonDepthLinear;
    QFrame *frame_5;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *labelFz_A;
    QLabel *labelFx_A;
    QLabel *labelFy_A;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_7;
    QLabel *labelTz_A;
    QLabel *labelTy_A;
    QLabel *labelTx_A;
    QLabel *label_4;
    QLabel *label_6;
    QLabel *label_5;
    QLabel *labelFx_B;
    QLabel *labelFy_B;
    QLabel *labelFz_B;
    QLabel *label_12;
    QLabel *label_11;
    QLabel *label_10;
    QLabel *labelTz_B;
    QLabel *labelTx_B;
    QLabel *labelTy_B;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QFrame *frameHaptRep_2;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLineEdit *lineEditDistance;
    QLineEdit *lineEditDeltaForce;
    QLineEdit *lineEditDeltaSlope;
    QLabel *label_44;
    QLabel *label_42;
    QLineEdit *lineEditForceMin;
    QWidget *tab;
    QFrame *frameHaptRep;
    QLabel *label_16;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLineEdit *lineEditHRFx;
    QLineEdit *lineEditHRTx;
    QLineEdit *lineEditHRFy;
    QLineEdit *lineEditHRTy;
    QLineEdit *lineEditHRFz;
    QLineEdit *lineEditHRTz;
    QRadioButton *radioButtonSideDom;
    QRadioButton *radioButtonSideNonDom;
    QLabel *label_26;
    QWidget *tab_3;
    QFrame *frameHaptRepAuto;
    QLabel *label_13;
    QLineEdit *lineEditExpFile;
    QLabel *label_30;
    QPushButton *pushButtonLoadExpFile;
    QLabel *label_31;
    QLabel *label_33;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *labelExpIndex;
    QLabel *labelExpDirection;
    QLabel *labelExpSign;
    QLabel *labelExpOutputHand;
    QLabel *labelExpOrder;
    QPushButton *pushButtonReadNextTrial;
    QLabel *labelExpMagnitude;
    QLabel *label_34;
    QLabel *label_32;
    QPushButton *pushButtonGoTo;
    QLineEdit *lineEditGoTo;
    QLabel *label_37;
    QLabel *labelIsRun;
    QLabel *label_43;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *labelExpDistance;
    QLabel *labelExpForceMin;
    QLabel *labelExpDelta;
    QPushButton *pushButtonZero;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *HapticEvaluationGUIClass)
    {
        if (HapticEvaluationGUIClass->objectName().isEmpty())
            HapticEvaluationGUIClass->setObjectName(QString::fromUtf8("HapticEvaluationGUIClass"));
        HapticEvaluationGUIClass->resize(1048, 860);
        centralWidget = new QWidget(HapticEvaluationGUIClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        pushButtonStart = new QPushButton(centralWidget);
        pushButtonStart->setObjectName(QString::fromUtf8("pushButtonStart"));
        pushButtonStart->setGeometry(QRect(940, 610, 75, 23));
        pushButtonStop = new QPushButton(centralWidget);
        pushButtonStop->setObjectName(QString::fromUtf8("pushButtonStop"));
        pushButtonStop->setGeometry(QRect(940, 670, 75, 23));
        labelStatus = new QLabel(centralWidget);
        labelStatus->setObjectName(QString::fromUtf8("labelStatus"));
        labelStatus->setGeometry(QRect(10, 770, 821, 20));
        labelStatus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qwtPlot = new QwtPlot(centralWidget);
        qwtPlot->setObjectName(QString::fromUtf8("qwtPlot"));
        qwtPlot->setGeometry(QRect(10, 50, 921, 231));
        qwtPlot->setMouseTracking(false);
        checkBoxFxA = new QCheckBox(centralWidget);
        checkBoxFxA->setObjectName(QString::fromUtf8("checkBoxFxA"));
        checkBoxFxA->setGeometry(QRect(950, 60, 51, 16));
        QFont font;
        font.setPointSize(8);
        checkBoxFxA->setFont(font);
        checkBoxFyA = new QCheckBox(centralWidget);
        checkBoxFyA->setObjectName(QString::fromUtf8("checkBoxFyA"));
        checkBoxFyA->setGeometry(QRect(950, 90, 51, 16));
        checkBoxFzA = new QCheckBox(centralWidget);
        checkBoxFzA->setObjectName(QString::fromUtf8("checkBoxFzA"));
        checkBoxFzA->setGeometry(QRect(950, 120, 51, 16));
        checkBoxFtotalA = new QCheckBox(centralWidget);
        checkBoxFtotalA->setObjectName(QString::fromUtf8("checkBoxFtotalA"));
        checkBoxFtotalA->setGeometry(QRect(950, 150, 61, 16));
        checkBoxFxB = new QCheckBox(centralWidget);
        checkBoxFxB->setObjectName(QString::fromUtf8("checkBoxFxB"));
        checkBoxFxB->setGeometry(QRect(950, 180, 71, 18));
        checkBoxFyB = new QCheckBox(centralWidget);
        checkBoxFyB->setObjectName(QString::fromUtf8("checkBoxFyB"));
        checkBoxFyB->setGeometry(QRect(950, 210, 71, 18));
        checkBoxFzB = new QCheckBox(centralWidget);
        checkBoxFzB->setObjectName(QString::fromUtf8("checkBoxFzB"));
        checkBoxFzB->setGeometry(QRect(950, 240, 71, 18));
        checkBoxFtotalB = new QCheckBox(centralWidget);
        checkBoxFtotalB->setObjectName(QString::fromUtf8("checkBoxFtotalB"));
        checkBoxFtotalB->setGeometry(QRect(950, 270, 71, 18));
        frameHaptBCtrl = new QFrame(centralWidget);
        frameHaptBCtrl->setObjectName(QString::fromUtf8("frameHaptBCtrl"));
        frameHaptBCtrl->setGeometry(QRect(790, 390, 151, 101));
        frameHaptBCtrl->setFrameShape(QFrame::StyledPanel);
        frameHaptBCtrl->setFrameShadow(QFrame::Raised);
        label_15 = new QLabel(frameHaptBCtrl);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(30, 0, 101, 21));
        lineEditEntactBIP = new QLineEdit(frameHaptBCtrl);
        lineEditEntactBIP->setObjectName(QString::fromUtf8("lineEditEntactBIP"));
        lineEditEntactBIP->setGeometry(QRect(50, 20, 81, 20));
        label_19 = new QLabel(frameHaptBCtrl);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(30, 20, 16, 16));
        checkBoxActiveEntactB = new QCheckBox(frameHaptBCtrl);
        checkBoxActiveEntactB->setObjectName(QString::fromUtf8("checkBoxActiveEntactB"));
        checkBoxActiveEntactB->setGeometry(QRect(30, 50, 71, 18));
        pushButtonEntactBCalibrate = new QPushButton(frameHaptBCtrl);
        pushButtonEntactBCalibrate->setObjectName(QString::fromUtf8("pushButtonEntactBCalibrate"));
        pushButtonEntactBCalibrate->setGeometry(QRect(40, 70, 75, 23));
        frameHaptACtrl = new QFrame(centralWidget);
        frameHaptACtrl->setObjectName(QString::fromUtf8("frameHaptACtrl"));
        frameHaptACtrl->setGeometry(QRect(640, 390, 151, 101));
        frameHaptACtrl->setFrameShape(QFrame::StyledPanel);
        frameHaptACtrl->setFrameShadow(QFrame::Raised);
        label_17 = new QLabel(frameHaptACtrl);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(30, 0, 101, 20));
        label_18 = new QLabel(frameHaptACtrl);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(30, 20, 16, 16));
        checkBoxActiveEntactA = new QCheckBox(frameHaptACtrl);
        checkBoxActiveEntactA->setObjectName(QString::fromUtf8("checkBoxActiveEntactA"));
        checkBoxActiveEntactA->setGeometry(QRect(30, 50, 71, 18));
        lineEditEntactAIP = new QLineEdit(frameHaptACtrl);
        lineEditEntactAIP->setObjectName(QString::fromUtf8("lineEditEntactAIP"));
        lineEditEntactAIP->setGeometry(QRect(50, 20, 81, 20));
        pushButtonEntactACalibrate = new QPushButton(frameHaptACtrl);
        pushButtonEntactACalibrate->setObjectName(QString::fromUtf8("pushButtonEntactACalibrate"));
        pushButtonEntactACalibrate->setGeometry(QRect(40, 70, 75, 23));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(210, 500, 201, 16));
        textEditExpInfo = new QTextEdit(centralWidget);
        textEditExpInfo->setObjectName(QString::fromUtf8("textEditExpInfo"));
        textEditExpInfo->setGeometry(QRect(210, 520, 201, 201));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(640, 300, 151, 81));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        lineEditLJSerialA = new QLineEdit(frame);
        lineEditLJSerialA->setObjectName(QString::fromUtf8("lineEditLJSerialA"));
        lineEditLJSerialA->setGeometry(QRect(20, 30, 113, 20));
        checkBoxAtiActivateA = new QCheckBox(frame);
        checkBoxAtiActivateA->setObjectName(QString::fromUtf8("checkBoxAtiActivateA"));
        checkBoxAtiActivateA->setGeometry(QRect(10, 60, 141, 20));
        label_27 = new QLabel(frame);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(20, 10, 131, 20));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(790, 300, 151, 81));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        lineEditLJSerialB = new QLineEdit(frame_2);
        lineEditLJSerialB->setObjectName(QString::fromUtf8("lineEditLJSerialB"));
        lineEditLJSerialB->setGeometry(QRect(20, 30, 113, 20));
        checkBoxAtiActivateB = new QCheckBox(frame_2);
        checkBoxAtiActivateB->setObjectName(QString::fromUtf8("checkBoxAtiActivateB"));
        checkBoxAtiActivateB->setGeometry(QRect(10, 60, 131, 18));
        label_28 = new QLabel(frame_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(20, 10, 131, 16));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(660, 540, 261, 91));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        labelFile = new QLabel(frame_3);
        labelFile->setObjectName(QString::fromUtf8("labelFile"));
        labelFile->setGeometry(QRect(10, 30, 41, 16));
        lineEditLog = new QLineEdit(frame_3);
        lineEditLog->setObjectName(QString::fromUtf8("lineEditLog"));
        lineEditLog->setGeometry(QRect(50, 30, 201, 21));
        labelFile_4 = new QLabel(frame_3);
        labelFile_4->setObjectName(QString::fromUtf8("labelFile_4"));
        labelFile_4->setGeometry(QRect(10, 60, 61, 16));
        radioButtonRight = new QRadioButton(frame_3);
        radioButtonRight->setObjectName(QString::fromUtf8("radioButtonRight"));
        radioButtonRight->setGeometry(QRect(140, 60, 51, 17));
        radioButtonLeft = new QRadioButton(frame_3);
        radioButtonLeft->setObjectName(QString::fromUtf8("radioButtonLeft"));
        radioButtonLeft->setGeometry(QRect(80, 60, 41, 17));
        label_29 = new QLabel(frame_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(70, 10, 81, 16));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(20, 500, 181, 261));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_14 = new QLabel(frame_4);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 0, 161, 16));
        radioButtonSLPosition = new QRadioButton(frame_4);
        radioButtonSLPosition->setObjectName(QString::fromUtf8("radioButtonSLPosition"));
        radioButtonSLPosition->setGeometry(QRect(10, 50, 151, 18));
        radioButtonSLForce = new QRadioButton(frame_4);
        radioButtonSLForce->setObjectName(QString::fromUtf8("radioButtonSLForce"));
        radioButtonSLForce->setGeometry(QRect(10, 70, 151, 18));
        radioButtonDLForce = new QRadioButton(frame_4);
        radioButtonDLForce->setObjectName(QString::fromUtf8("radioButtonDLForce"));
        radioButtonDLForce->setGeometry(QRect(10, 90, 131, 18));
        radioButtonHaptRep = new QRadioButton(frame_4);
        radioButtonHaptRep->setObjectName(QString::fromUtf8("radioButtonHaptRep"));
        radioButtonHaptRep->setGeometry(QRect(10, 110, 171, 16));
        radioButtonATIOnly = new QRadioButton(frame_4);
        radioButtonATIOnly->setObjectName(QString::fromUtf8("radioButtonATIOnly"));
        radioButtonATIOnly->setGeometry(QRect(10, 30, 82, 18));
        radioButtonHRSeq = new QRadioButton(frame_4);
        radioButtonHRSeq->setObjectName(QString::fromUtf8("radioButtonHRSeq"));
        radioButtonHRSeq->setGeometry(QRect(10, 130, 161, 18));
        radioButtonHaptRepAuto = new QRadioButton(frame_4);
        radioButtonHaptRepAuto->setObjectName(QString::fromUtf8("radioButtonHaptRepAuto"));
        radioButtonHaptRepAuto->setGeometry(QRect(10, 150, 141, 18));
        radioButtonSingleHaptic = new QRadioButton(frame_4);
        radioButtonSingleHaptic->setObjectName(QString::fromUtf8("radioButtonSingleHaptic"));
        radioButtonSingleHaptic->setGeometry(QRect(10, 170, 141, 18));
        radioButtonDepthConstant = new QRadioButton(frame_4);
        radioButtonDepthConstant->setObjectName(QString::fromUtf8("radioButtonDepthConstant"));
        radioButtonDepthConstant->setGeometry(QRect(10, 190, 141, 18));
        radioButtonDepthLinear = new QRadioButton(frame_4);
        radioButtonDepthLinear->setObjectName(QString::fromUtf8("radioButtonDepthLinear"));
        radioButtonDepthLinear->setGeometry(QRect(10, 210, 141, 18));
        radioButtonSLPosition->raise();
        radioButtonSLForce->raise();
        radioButtonDLForce->raise();
        radioButtonHaptRep->raise();
        radioButtonATIOnly->raise();
        radioButtonHRSeq->raise();
        radioButtonHaptRepAuto->raise();
        radioButtonSingleHaptic->raise();
        radioButtonDepthConstant->raise();
        radioButtonDepthLinear->raise();
        label_14->raise();
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(10, 300, 621, 191));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        label = new QLabel(frame_5);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 51, 16));
        label_2 = new QLabel(frame_5);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 80, 51, 16));
        label_3 = new QLabel(frame_5);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 140, 51, 16));
        labelFz_A = new QLabel(frame_5);
        labelFz_A->setObjectName(QString::fromUtf8("labelFz_A"));
        labelFz_A->setGeometry(QRect(70, 140, 46, 13));
        labelFx_A = new QLabel(frame_5);
        labelFx_A->setObjectName(QString::fromUtf8("labelFx_A"));
        labelFx_A->setGeometry(QRect(70, 20, 46, 13));
        labelFy_A = new QLabel(frame_5);
        labelFy_A->setObjectName(QString::fromUtf8("labelFy_A"));
        labelFy_A->setGeometry(QRect(70, 80, 46, 13));
        label_8 = new QLabel(frame_5);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(140, 20, 61, 16));
        label_9 = new QLabel(frame_5);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(140, 80, 61, 16));
        label_7 = new QLabel(frame_5);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(140, 140, 61, 16));
        labelTz_A = new QLabel(frame_5);
        labelTz_A->setObjectName(QString::fromUtf8("labelTz_A"));
        labelTz_A->setGeometry(QRect(220, 140, 46, 13));
        labelTy_A = new QLabel(frame_5);
        labelTy_A->setObjectName(QString::fromUtf8("labelTy_A"));
        labelTy_A->setGeometry(QRect(220, 80, 46, 13));
        labelTx_A = new QLabel(frame_5);
        labelTx_A->setObjectName(QString::fromUtf8("labelTx_A"));
        labelTx_A->setGeometry(QRect(220, 20, 46, 13));
        label_4 = new QLabel(frame_5);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(350, 20, 51, 16));
        label_6 = new QLabel(frame_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(350, 140, 51, 16));
        label_5 = new QLabel(frame_5);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(350, 80, 51, 16));
        labelFx_B = new QLabel(frame_5);
        labelFx_B->setObjectName(QString::fromUtf8("labelFx_B"));
        labelFx_B->setGeometry(QRect(420, 20, 46, 13));
        labelFy_B = new QLabel(frame_5);
        labelFy_B->setObjectName(QString::fromUtf8("labelFy_B"));
        labelFy_B->setGeometry(QRect(420, 80, 46, 13));
        labelFz_B = new QLabel(frame_5);
        labelFz_B->setObjectName(QString::fromUtf8("labelFz_B"));
        labelFz_B->setGeometry(QRect(420, 140, 46, 13));
        label_12 = new QLabel(frame_5);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(490, 140, 61, 16));
        label_11 = new QLabel(frame_5);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(490, 80, 61, 16));
        label_10 = new QLabel(frame_5);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(490, 20, 61, 16));
        labelTz_B = new QLabel(frame_5);
        labelTz_B->setObjectName(QString::fromUtf8("labelTz_B"));
        labelTz_B->setGeometry(QRect(560, 140, 46, 13));
        labelTx_B = new QLabel(frame_5);
        labelTx_B->setObjectName(QString::fromUtf8("labelTx_B"));
        labelTx_B->setGeometry(QRect(560, 20, 46, 13));
        labelTy_B = new QLabel(frame_5);
        labelTy_B->setObjectName(QString::fromUtf8("labelTy_B"));
        labelTy_B->setGeometry(QRect(560, 80, 46, 13));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(416, 500, 251, 301));
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        frameHaptRep_2 = new QFrame(tab_2);
        frameHaptRep_2->setObjectName(QString::fromUtf8("frameHaptRep_2"));
        frameHaptRep_2->setGeometry(QRect(20, 20, 191, 181));
        frameHaptRep_2->setFrameShape(QFrame::StyledPanel);
        frameHaptRep_2->setFrameShadow(QFrame::Raised);
        label_38 = new QLabel(frameHaptRep_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 0, 151, 16));
        label_39 = new QLabel(frameHaptRep_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 40, 101, 16));
        label_40 = new QLabel(frameHaptRep_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 60, 91, 16));
        label_41 = new QLabel(frameHaptRep_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 80, 91, 16));
        lineEditDistance = new QLineEdit(frameHaptRep_2);
        lineEditDistance->setObjectName(QString::fromUtf8("lineEditDistance"));
        lineEditDistance->setGeometry(QRect(110, 40, 51, 20));
        lineEditDeltaForce = new QLineEdit(frameHaptRep_2);
        lineEditDeltaForce->setObjectName(QString::fromUtf8("lineEditDeltaForce"));
        lineEditDeltaForce->setGeometry(QRect(110, 60, 51, 20));
        lineEditDeltaSlope = new QLineEdit(frameHaptRep_2);
        lineEditDeltaSlope->setObjectName(QString::fromUtf8("lineEditDeltaSlope"));
        lineEditDeltaSlope->setGeometry(QRect(110, 80, 51, 20));
        label_44 = new QLabel(frameHaptRep_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(0, 140, 181, 31));
        label_42 = new QLabel(frameHaptRep_2);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 110, 91, 16));
        lineEditForceMin = new QLineEdit(frameHaptRep_2);
        lineEditForceMin->setObjectName(QString::fromUtf8("lineEditForceMin"));
        lineEditForceMin->setGeometry(QRect(110, 110, 51, 20));
        tabWidget->addTab(tab_2, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        frameHaptRep = new QFrame(tab);
        frameHaptRep->setObjectName(QString::fromUtf8("frameHaptRep"));
        frameHaptRep->setGeometry(QRect(40, 20, 161, 171));
        frameHaptRep->setFrameShape(QFrame::StyledPanel);
        frameHaptRep->setFrameShadow(QFrame::Raised);
        label_16 = new QLabel(frameHaptRep);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 0, 151, 16));
        label_20 = new QLabel(frameHaptRep);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 40, 16, 16));
        label_21 = new QLabel(frameHaptRep);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 60, 16, 16));
        label_22 = new QLabel(frameHaptRep);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 80, 16, 16));
        label_23 = new QLabel(frameHaptRep);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(20, 20, 46, 13));
        label_24 = new QLabel(frameHaptRep);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(80, 20, 71, 16));
        lineEditHRFx = new QLineEdit(frameHaptRep);
        lineEditHRFx->setObjectName(QString::fromUtf8("lineEditHRFx"));
        lineEditHRFx->setGeometry(QRect(20, 40, 51, 20));
        lineEditHRTx = new QLineEdit(frameHaptRep);
        lineEditHRTx->setObjectName(QString::fromUtf8("lineEditHRTx"));
        lineEditHRTx->setGeometry(QRect(90, 40, 51, 20));
        lineEditHRFy = new QLineEdit(frameHaptRep);
        lineEditHRFy->setObjectName(QString::fromUtf8("lineEditHRFy"));
        lineEditHRFy->setGeometry(QRect(20, 60, 51, 20));
        lineEditHRTy = new QLineEdit(frameHaptRep);
        lineEditHRTy->setObjectName(QString::fromUtf8("lineEditHRTy"));
        lineEditHRTy->setGeometry(QRect(90, 60, 51, 20));
        lineEditHRFz = new QLineEdit(frameHaptRep);
        lineEditHRFz->setObjectName(QString::fromUtf8("lineEditHRFz"));
        lineEditHRFz->setGeometry(QRect(20, 80, 51, 20));
        lineEditHRTz = new QLineEdit(frameHaptRep);
        lineEditHRTz->setObjectName(QString::fromUtf8("lineEditHRTz"));
        lineEditHRTz->setGeometry(QRect(90, 80, 51, 20));
        radioButtonSideDom = new QRadioButton(frameHaptRep);
        radioButtonSideDom->setObjectName(QString::fromUtf8("radioButtonSideDom"));
        radioButtonSideDom->setGeometry(QRect(10, 130, 111, 16));
        radioButtonSideNonDom = new QRadioButton(frameHaptRep);
        radioButtonSideNonDom->setObjectName(QString::fromUtf8("radioButtonSideNonDom"));
        radioButtonSideNonDom->setGeometry(QRect(10, 150, 101, 16));
        label_26 = new QLabel(frameHaptRep);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 110, 111, 16));
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        frameHaptRepAuto = new QFrame(tab_3);
        frameHaptRepAuto->setObjectName(QString::fromUtf8("frameHaptRepAuto"));
        frameHaptRepAuto->setGeometry(QRect(10, 0, 221, 281));
        frameHaptRepAuto->setFrameShape(QFrame::StyledPanel);
        frameHaptRepAuto->setFrameShadow(QFrame::Raised);
        label_13 = new QLabel(frameHaptRepAuto);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(40, 0, 121, 20));
        lineEditExpFile = new QLineEdit(frameHaptRepAuto);
        lineEditExpFile->setObjectName(QString::fromUtf8("lineEditExpFile"));
        lineEditExpFile->setGeometry(QRect(62, 20, 141, 20));
        label_30 = new QLabel(frameHaptRepAuto);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 20, 46, 13));
        pushButtonLoadExpFile = new QPushButton(frameHaptRepAuto);
        pushButtonLoadExpFile->setObjectName(QString::fromUtf8("pushButtonLoadExpFile"));
        pushButtonLoadExpFile->setGeometry(QRect(60, 40, 75, 23));
        label_31 = new QLabel(frameHaptRepAuto);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(50, 60, 31, 16));
        label_33 = new QLabel(frameHaptRepAuto);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(30, 100, 51, 16));
        label_35 = new QLabel(frameHaptRepAuto);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 140, 61, 16));
        label_36 = new QLabel(frameHaptRepAuto);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(40, 160, 31, 16));
        label_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelExpIndex = new QLabel(frameHaptRepAuto);
        labelExpIndex->setObjectName(QString::fromUtf8("labelExpIndex"));
        labelExpIndex->setGeometry(QRect(100, 60, 91, 16));
        labelExpDirection = new QLabel(frameHaptRepAuto);
        labelExpDirection->setObjectName(QString::fromUtf8("labelExpDirection"));
        labelExpDirection->setGeometry(QRect(100, 100, 91, 16));
        labelExpSign = new QLabel(frameHaptRepAuto);
        labelExpSign->setObjectName(QString::fromUtf8("labelExpSign"));
        labelExpSign->setGeometry(QRect(100, 80, 91, 16));
        labelExpOutputHand = new QLabel(frameHaptRepAuto);
        labelExpOutputHand->setObjectName(QString::fromUtf8("labelExpOutputHand"));
        labelExpOutputHand->setGeometry(QRect(100, 140, 91, 16));
        labelExpOrder = new QLabel(frameHaptRepAuto);
        labelExpOrder->setObjectName(QString::fromUtf8("labelExpOrder"));
        labelExpOrder->setGeometry(QRect(100, 160, 91, 16));
        pushButtonReadNextTrial = new QPushButton(frameHaptRepAuto);
        pushButtonReadNextTrial->setObjectName(QString::fromUtf8("pushButtonReadNextTrial"));
        pushButtonReadNextTrial->setGeometry(QRect(10, 230, 81, 23));
        labelExpMagnitude = new QLabel(frameHaptRepAuto);
        labelExpMagnitude->setObjectName(QString::fromUtf8("labelExpMagnitude"));
        labelExpMagnitude->setGeometry(QRect(100, 120, 91, 16));
        label_34 = new QLabel(frameHaptRepAuto);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(50, 80, 31, 16));
        label_32 = new QLabel(frameHaptRepAuto);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 120, 71, 16));
        pushButtonGoTo = new QPushButton(frameHaptRepAuto);
        pushButtonGoTo->setObjectName(QString::fromUtf8("pushButtonGoTo"));
        pushButtonGoTo->setGeometry(QRect(100, 230, 61, 23));
        lineEditGoTo = new QLineEdit(frameHaptRepAuto);
        lineEditGoTo->setObjectName(QString::fromUtf8("lineEditGoTo"));
        lineEditGoTo->setGeometry(QRect(170, 230, 41, 20));
        label_37 = new QLabel(frameHaptRepAuto);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 260, 31, 16));
        labelIsRun = new QLabel(frameHaptRepAuto);
        labelIsRun->setObjectName(QString::fromUtf8("labelIsRun"));
        labelIsRun->setGeometry(QRect(45, 260, 51, 16));
        label_43 = new QLabel(frameHaptRepAuto);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(30, 179, 41, 16));
        label_43->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_45 = new QLabel(frameHaptRepAuto);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(40, 189, 31, 30));
        label_45->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_46 = new QLabel(frameHaptRepAuto);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(0, 210, 71, 20));
        label_46->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelExpDistance = new QLabel(frameHaptRepAuto);
        labelExpDistance->setObjectName(QString::fromUtf8("labelExpDistance"));
        labelExpDistance->setGeometry(QRect(100, 179, 91, 16));
        labelExpForceMin = new QLabel(frameHaptRepAuto);
        labelExpForceMin->setObjectName(QString::fromUtf8("labelExpForceMin"));
        labelExpForceMin->setGeometry(QRect(100, 210, 91, 16));
        labelExpDelta = new QLabel(frameHaptRepAuto);
        labelExpDelta->setObjectName(QString::fromUtf8("labelExpDelta"));
        labelExpDelta->setGeometry(QRect(100, 192, 91, 20));
        tabWidget->addTab(tab_3, QString());
        pushButtonZero = new QPushButton(centralWidget);
        pushButtonZero->setObjectName(QString::fromUtf8("pushButtonZero"));
        pushButtonZero->setGeometry(QRect(940, 640, 75, 23));
        HapticEvaluationGUIClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(HapticEvaluationGUIClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1048, 21));
        HapticEvaluationGUIClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(HapticEvaluationGUIClass);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        HapticEvaluationGUIClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(HapticEvaluationGUIClass);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        HapticEvaluationGUIClass->setStatusBar(statusBar);

        retranslateUi(HapticEvaluationGUIClass);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(HapticEvaluationGUIClass);
    } // setupUi

    void retranslateUi(QMainWindow *HapticEvaluationGUIClass)
    {
        HapticEvaluationGUIClass->setWindowTitle(QApplication::translate("HapticEvaluationGUIClass", "HapticEvaluationGUI", 0, QApplication::UnicodeUTF8));
        pushButtonStart->setText(QApplication::translate("HapticEvaluationGUIClass", "Start", 0, QApplication::UnicodeUTF8));
        pushButtonStop->setText(QApplication::translate("HapticEvaluationGUIClass", "Stop", 0, QApplication::UnicodeUTF8));
        labelStatus->setText(QApplication::translate("HapticEvaluationGUIClass", "Status", 0, QApplication::UnicodeUTF8));
        checkBoxFxA->setText(QApplication::translate("HapticEvaluationGUIClass", "Fx_A", 0, QApplication::UnicodeUTF8));
        checkBoxFyA->setText(QApplication::translate("HapticEvaluationGUIClass", "Fy_A", 0, QApplication::UnicodeUTF8));
        checkBoxFzA->setText(QApplication::translate("HapticEvaluationGUIClass", "Fz_A", 0, QApplication::UnicodeUTF8));
        checkBoxFtotalA->setText(QApplication::translate("HapticEvaluationGUIClass", "Ftotal_A", 0, QApplication::UnicodeUTF8));
        checkBoxFxB->setText(QApplication::translate("HapticEvaluationGUIClass", "Fx_B", 0, QApplication::UnicodeUTF8));
        checkBoxFyB->setText(QApplication::translate("HapticEvaluationGUIClass", "Fy_B", 0, QApplication::UnicodeUTF8));
        checkBoxFzB->setText(QApplication::translate("HapticEvaluationGUIClass", "Fz_B", 0, QApplication::UnicodeUTF8));
        checkBoxFtotalB->setText(QApplication::translate("HapticEvaluationGUIClass", "Ftotal_B", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("HapticEvaluationGUIClass", "Right Entact Controls", 0, QApplication::UnicodeUTF8));
        lineEditEntactBIP->setText(QApplication::translate("HapticEvaluationGUIClass", "192.168.1.101", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("HapticEvaluationGUIClass", "IP", 0, QApplication::UnicodeUTF8));
        checkBoxActiveEntactB->setText(QApplication::translate("HapticEvaluationGUIClass", "Activate", 0, QApplication::UnicodeUTF8));
        pushButtonEntactBCalibrate->setText(QApplication::translate("HapticEvaluationGUIClass", "Calibrate", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("HapticEvaluationGUIClass", "Left Entact Controls", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("HapticEvaluationGUIClass", "IP", 0, QApplication::UnicodeUTF8));
        checkBoxActiveEntactA->setText(QApplication::translate("HapticEvaluationGUIClass", "Activate", 0, QApplication::UnicodeUTF8));
        lineEditEntactAIP->setText(QApplication::translate("HapticEvaluationGUIClass", "192.168.0.101", 0, QApplication::UnicodeUTF8));
        pushButtonEntactACalibrate->setText(QApplication::translate("HapticEvaluationGUIClass", "Calibrate", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("HapticEvaluationGUIClass", "Control Scheme/Experiment Information", 0, QApplication::UnicodeUTF8));
        lineEditLJSerialA->setText(QApplication::translate("HapticEvaluationGUIClass", "360008763", 0, QApplication::UnicodeUTF8));
        checkBoxAtiActivateA->setText(QApplication::translate("HapticEvaluationGUIClass", "ATI A FT09498 Activate", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("HapticEvaluationGUIClass", "LabJack A Serial (left)", 0, QApplication::UnicodeUTF8));
        lineEditLJSerialB->setText(QApplication::translate("HapticEvaluationGUIClass", "360005412", 0, QApplication::UnicodeUTF8));
        checkBoxAtiActivateB->setText(QApplication::translate("HapticEvaluationGUIClass", "ATI B FT13441 Activate", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("HapticEvaluationGUIClass", "LabJack B Serial (right)", 0, QApplication::UnicodeUTF8));
        labelFile->setText(QApplication::translate("HapticEvaluationGUIClass", "Log File", 0, QApplication::UnicodeUTF8));
        labelFile_4->setText(QApplication::translate("HapticEvaluationGUIClass", "Preference", 0, QApplication::UnicodeUTF8));
        radioButtonRight->setText(QApplication::translate("HapticEvaluationGUIClass", "Right", 0, QApplication::UnicodeUTF8));
        radioButtonLeft->setText(QApplication::translate("HapticEvaluationGUIClass", "Left", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("HapticEvaluationGUIClass", "Logger Settings", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("HapticEvaluationGUIClass", "Control Scheme/Experiment Type", 0, QApplication::UnicodeUTF8));
        radioButtonSLPosition->setText(QApplication::translate("HapticEvaluationGUIClass", "Single Link Position Control", 0, QApplication::UnicodeUTF8));
        radioButtonSLForce->setText(QApplication::translate("HapticEvaluationGUIClass", "Single Link Force Control", 0, QApplication::UnicodeUTF8));
        radioButtonDLForce->setText(QApplication::translate("HapticEvaluationGUIClass", "Dual Link Force Control", 0, QApplication::UnicodeUTF8));
        radioButtonHaptRep->setText(QApplication::translate("HapticEvaluationGUIClass", "Haptic Replication Simultaneous", 0, QApplication::UnicodeUTF8));
        radioButtonATIOnly->setText(QApplication::translate("HapticEvaluationGUIClass", "Use ATI Only", 0, QApplication::UnicodeUTF8));
        radioButtonHRSeq->setText(QApplication::translate("HapticEvaluationGUIClass", "Haptic Replication Sequential", 0, QApplication::UnicodeUTF8));
        radioButtonHaptRepAuto->setText(QApplication::translate("HapticEvaluationGUIClass", "Haptic Replication Auto", 0, QApplication::UnicodeUTF8));
        radioButtonSingleHaptic->setText(QApplication::translate("HapticEvaluationGUIClass", "Single Force Feedback", 0, QApplication::UnicodeUTF8));
        radioButtonDepthConstant->setText(QApplication::translate("HapticEvaluationGUIClass", " Force with Depth constant", 0, QApplication::UnicodeUTF8));
        radioButtonDepthLinear->setText(QApplication::translate("HapticEvaluationGUIClass", " Force with Depth linear", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("HapticEvaluationGUIClass", "Force X_A", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("HapticEvaluationGUIClass", "Force Y_A", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("HapticEvaluationGUIClass", "Force Z_A", 0, QApplication::UnicodeUTF8));
        labelFz_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Fz_A", 0, QApplication::UnicodeUTF8));
        labelFx_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Fx_A", 0, QApplication::UnicodeUTF8));
        labelFy_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Fy_A", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque X_A", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque Y_A", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque Z_A", 0, QApplication::UnicodeUTF8));
        labelTz_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Tz_A", 0, QApplication::UnicodeUTF8));
        labelTy_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Ty_A", 0, QApplication::UnicodeUTF8));
        labelTx_A->setText(QApplication::translate("HapticEvaluationGUIClass", "Tx_A", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("HapticEvaluationGUIClass", "Force X_B", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("HapticEvaluationGUIClass", "Force Z_B", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("HapticEvaluationGUIClass", "Force Y_B", 0, QApplication::UnicodeUTF8));
        labelFx_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Fx_B", 0, QApplication::UnicodeUTF8));
        labelFy_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Fy_B", 0, QApplication::UnicodeUTF8));
        labelFz_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Fz_B", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque Z_B", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque Y_B", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque X_B", 0, QApplication::UnicodeUTF8));
        labelTz_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Tz_B", 0, QApplication::UnicodeUTF8));
        labelTx_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Tx_B", 0, QApplication::UnicodeUTF8));
        labelTy_B->setText(QApplication::translate("HapticEvaluationGUIClass", "Ty_B", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("HapticEvaluationGUIClass", "Settings for Depth Force Control", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("HapticEvaluationGUIClass", "distance (mm)", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("HapticEvaluationGUIClass", "delta force (N)", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("HapticEvaluationGUIClass", "delta slope (0-1)", 0, QApplication::UnicodeUTF8));
        lineEditDistance->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditDeltaForce->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditDeltaSlope->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("HapticEvaluationGUIClass", "<html><head/><body><p>Preference control on the right <br/>says which device is used (L/R)</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("HapticEvaluationGUIClass", "Force min (N)", 0, QApplication::UnicodeUTF8));
        lineEditForceMin->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("HapticEvaluationGUIClass", "Depth", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("HapticEvaluationGUIClass", "Settings for Haptic Replication", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("HapticEvaluationGUIClass", "X", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("HapticEvaluationGUIClass", "Y", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("HapticEvaluationGUIClass", "Z", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("HapticEvaluationGUIClass", "Force (N)", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("HapticEvaluationGUIClass", "Torque (N.mm)", 0, QApplication::UnicodeUTF8));
        lineEditHRFx->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditHRTx->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditHRFy->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditHRTy->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditHRFz->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        lineEditHRTz->setText(QApplication::translate("HapticEvaluationGUIClass", "0", 0, QApplication::UnicodeUTF8));
        radioButtonSideDom->setText(QApplication::translate("HapticEvaluationGUIClass", "Dominant", 0, QApplication::UnicodeUTF8));
        radioButtonSideNonDom->setText(QApplication::translate("HapticEvaluationGUIClass", "Non-Dominant", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("HapticEvaluationGUIClass", "Side to output force", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("HapticEvaluationGUIClass", "Repl", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("HapticEvaluationGUIClass", "Auto Hapt Rep Controls", 0, QApplication::UnicodeUTF8));
        lineEditExpFile->setText(QApplication::translate("HapticEvaluationGUIClass", ".xml", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("HapticEvaluationGUIClass", "Input file", 0, QApplication::UnicodeUTF8));
        pushButtonLoadExpFile->setText(QApplication::translate("HapticEvaluationGUIClass", "Load File", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("HapticEvaluationGUIClass", "Index", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("HapticEvaluationGUIClass", " Direction", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("HapticEvaluationGUIClass", "Output Hand", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("HapticEvaluationGUIClass", " Order", 0, QApplication::UnicodeUTF8));
        labelExpIndex->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpDirection->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpSign->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpOutputHand->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpOrder->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        pushButtonReadNextTrial->setText(QApplication::translate("HapticEvaluationGUIClass", "Load Next Trial", 0, QApplication::UnicodeUTF8));
        labelExpMagnitude->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("HapticEvaluationGUIClass", " Sign", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("HapticEvaluationGUIClass", "Magnitude (N)", 0, QApplication::UnicodeUTF8));
        pushButtonGoTo->setText(QApplication::translate("HapticEvaluationGUIClass", "Go To Trial", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("HapticEvaluationGUIClass", "Run?:", 0, QApplication::UnicodeUTF8));
        labelIsRun->setText(QApplication::translate("HapticEvaluationGUIClass", "No", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("HapticEvaluationGUIClass", "Distance", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("HapticEvaluationGUIClass", "Delta", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("HapticEvaluationGUIClass", "Force Min", 0, QApplication::UnicodeUTF8));
        labelExpDistance->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpForceMin->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        labelExpDelta->setText(QApplication::translate("HapticEvaluationGUIClass", "____", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("HapticEvaluationGUIClass", "Auto", 0, QApplication::UnicodeUTF8));
        pushButtonZero->setText(QApplication::translate("HapticEvaluationGUIClass", "Zero", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class HapticEvaluationGUIClass: public Ui_HapticEvaluationGUIClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HAPTICEVALUATIONGUI_H
